name: pine64-kernel
version: 3.10.104-2
summary: A pine64 kernel built from source
description: This is longsleep Pine64 kernel from linux-pine64 branch pine64-hacks-1.2
type: kernel
architectures: [ arm64 ]

parts:
    kernel:
        plugin: kernel
        source: https://github.com/longsleep/linux-pine64.git
        source-branch: pine64-hacks-1.2
        source-type: git
        kdefconfig: [sun50iw1p1smp_linux_defconfig]
        kconfigs:
            - CONFIG_LOCALVERSION="-pine64-longsleep"
            - CONFIG_SQUASHFS=m
            - CONFIG_SQUASHFS_XZ=y
            - CONFIG_SQUASHFS_LZO=y
            - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
            - CONFIG_CFG80211=y
        kernel-initrd-modules:
            - squashfs
        kernel-image-target: Image
        build-packages: [bc, kmod, cpio]
